mode = "server"
log_level = "debug" # optional

[trojan]
password = "PASSWORD"
fallback_addr = "127.0.0.1:80"

[tls]
addr = "0.0.0.0:443"
sni = "SERVERNAME"
cert = "/etc/letsencrypt/live/SERVERNAME/fullchain.pem"
key = "/etc/letsencrypt/live/SERVERNAME/privkey.pem"

#optional
#[websocket]
#path = "/trojanpath"
